version: '3.9'
services:
  helpme-iudigital:
    build:
      context: .
    ports:
      - "4343:4343"
    environment:
      DATABASE_URL: jdbc:mysql://basedatos:3306/helpme_iud_app_db?createDatabaseIfNotExist=true
      DATABASE_USERNAME: iud
      DATABASE_PASSWORD: Primera_123!
    networks:
      - iudigital
    depends_on:
      - basedatos
    restart: always
  basedatos:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Primera_123!
      MYSQL_DATABASE: helpme_iud_app_db
      MYSQL_USER: iud
      MYSQL_PASSWORD: Primera_123!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - iudigital

networks:
  iudigital:

volumes:
  db_data: