server:
  port: 4444
  servlet:
    context-path: /api/v1
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

spring:
  application:
    name: HelpmeIudApplication

  datasource:
    url: jdbc:mysql://localhost:3306/helpme_iud_app_db?createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
#    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: camilo.agudelob@est.iudigital.edu.co
    password: agudelob_cam_c#_2024_guacharnaca
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    client-service: HelpmeIUD
    password-service: 123456
    scope-read: read
    scope-write: write
    grant-password: password
    grant-refresh: refresh_token
    token-validity-seconds: 3600
    refresh-validity-seconds: 3600
    expiration: 3600000
    secret: aksfdñli28349aksfñladksf_kflksadfMsdflkasdlf#skflkasdfkkkasdkfl3243